controller_manager:
  ros__parameters:
    update_rate: 60
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    # forward_velocity_controller:
    #   type: forward_command_controller/ForwardCommandController

    omni_wheel_drive_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController

    lift_controller:
      type: position_controllers/JointGroupPositionController

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      # type: position_controller/GripperActionController

    right_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      # type: position_controller/GripperActionController

    left_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    left_forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    left_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    right_forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    right_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_servo_controller:
      type: position_controllers/JointGroupPositionController

forward_velocity_controller:
  ros__parameters:
    joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - br_wheel_joint
      - bl_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity

omni_wheel_drive_controller:
  ros__parameters:
    wheel_offset: 0.7853981633974485
    wheel_names:
      ["fl_wheel_joint", "bl_wheel_joint", "br_wheel_joint", "fr_wheel_joint"]

    robot_radius: 0.252
    wheel_radius: 0.076

    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    open_loop: true
    position_feedback: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true

lift_controller:
  ros__parameters:
    joints:
      - lift_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

arm_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
      - openarm_left_finger_joint1
      - openarm_right_finger_joint1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_arm_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_arm_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_gripper_controller:
  ros__parameters:
    joints:
      - openarm_left_finger_joint1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_gripper_controller:
  ros__parameters:
    joints:
      - openarm_right_finger_joint1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_forward_position_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position

left_forward_velocity_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity

left_joint_trajectory_controller:
  ros__parameters:
    joints:
      - openarm_left_joint1
      - openarm_left_joint2
      - openarm_left_joint3
      - openarm_left_joint4
      - openarm_left_joint5
      - openarm_left_joint6
      - openarm_left_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 50.0

    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

right_forward_position_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position

right_forward_velocity_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity

right_joint_trajectory_controller:
  ros__parameters:
    joints:
      - openarm_right_joint1
      - openarm_right_joint2
      - openarm_right_joint3
      - openarm_right_joint4
      - openarm_right_joint5
      - openarm_right_joint6
      - openarm_right_joint7
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 50.0

    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

head_servo_controller:
  ros__parameters:
    joints:
      - head_servo_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop: true
    allow_nonzero_velocity_at_steady_state: true
